### ISSUE TITLE
Query editor crashes when incorrectly creating a function

### ISSUE THREAD

**Issue by zerosym** [edgedb/edgedb-ui#145]
Environment:
Docker nightly 3-dev7241, Chrome browser

To reproduce:
In the query editor run `create function test` without trailing semi.

Crashes with:
**Something went wrong rendering this view**

```
Traceback:
RangeError: Mark decorations may not be empty
    at n.value (http://localhost:5656/ui/static/js/main.21807f5f.js:2:928075)
    at JL (http://localhost:5656/ui/static/js/main.21807f5f.js:2:1216499)
    at http://localhost:5656/ui/static/js/main.21807f5f.js:2:1221845
    at gs (http://localhost:5656/ui/static/js/main.21807f5f.js:2:316111)
    at Tu (http://localhost:5656/ui/static/js/main.21807f5f.js:2:333229)
    at t.unstable_runWithPriority (http://localhost:5656/ui/static/js/main.21807f5f.js:2:368341)
    at Qi (http://localhost:5656/ui/static/js/main.21807f5f.js:2:275096)
    at Nu (http://localhost:5656/ui/static/js/main.21807f5f.js:2:329964)
    at bu (http://localhost:5656/ui/static/js/main.21807f5f.js:2:326050)
    at http://localhost:5656/ui/static/js/main.21807f5f.js:2:275319```

**Comment by zerosym** [comment]
Just noticed this:
https://github.com/edgedb/edgedb-ui/issues/102

`Query Builder crashes with empty schema` -- guessing it's related?
